/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : CURL
 #	author : jelle
 #	06/09/09
 #
 # --------------------------------------------------------------------------------*/


enum{
	eCMD_Get_URL_Blob = 1,
	eCMD_Get_URL_Text
};
void InitPlugin();
void DeinitPlugin();

// --- CURL
void Get_URL_Blob( PA_PluginParameters params );
void Get_URL_Text( PA_PluginParameters params );
